### PR TITLE
modifify validators docs

### LINKED ISSUE #229: docs(validator): Validator.min and .max examples
https://docs.astro-reactive.dev/en/api/validator/validators/#validatorsmin

☝️ the example code for `Validators.min` and `Validators.max` are better with `type: number`

```ts
const form = new FormGroup([
  {
    name: "price",
    label: "Price",
    type: "number",
    validators: [Validators.min(8)],
  },
]);

```

### PR DESCRIPTION
**Pull request by Preet-Sojitra**
## docs(validator): Modifiy validators docs

Fixes #229 

Modified validators.min and validators.max docs as mentioned in issue #229 .
Tag a reviewer: @ayoayco 
Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by Preet-Sojitra** [comment]
> ### ❌ Deploy Preview for _astro-reactive-docs_ failed.
> Name 	Link
> 🔨 Latest commit 	[92f237e](https://github.com/ayoayco/astro-reactive-library/commit/92f237e05394be46d20b1717b730d4500b719ff7)
> 🔍 Latest deploy log 	https://app.netlify.com/sites/astro-reactive-docs/deploys/639308ffcbb39a0009c2dae6

Why this has failed? 🤔

**Review by ayoayco — CHANGES_REQUESTED** [review]
Hey @Lalit3716 I see formatting that's different from what I get whey I do "Format Document" on VS Code... can you try running it?

**Comment by Lalit3716** [comment]
Yeah, the formatting is incorrect on this PR. For me, it formats it like it was before when I run "Format Code".

**Comment by Preet-Sojitra** [comment]
> Hey @Lalit3716 @Preet-Sojitra I see some formatting that's different from what I get whey I do "Format Document" on VS Code... can you try running it?

ok, so what I have to run??

**Comment by Preet-Sojitra** [comment]
> > Hey @Lalit3716 @Preet-Sojitra I see some formatting that's different from what I get whey I do "Format Document" on VS Code... can you try running it?
> 
> ok, so what I have to run??

@ayoayco

**Comment by Lalit3716** [comment]
@Preet-Sojitra Do you have prettier installed on your vs code?

**Comment by Preet-Sojitra** [comment]
> @Preet-Sojitra Do you have prettier installed on your vs code?

Yess, and it auto formats when I save the changes

**Comment by ayoayco** [comment]
Can you see if you are using this exact "Prettier" extension on VS Code? @Preet-Sojitra 
Screenshot 2022-12-16 at 1 46 11 PM

**Comment by Preet-Sojitra** [comment]
> Can you see if you are using this exact "Prettier" extension on VS Code? @Preet-Sojitra Screenshot 2022-12-16 at 1 46 11 PM

Yup i guess this is the same which I have installed. 
image
But i guess i have configured it like when coding with JS related frameworks, on save it automatically removes semicolons . 

And one more question, can't we have universal linting? I mean can we have something like that which formats the code same for everybody, like my formatting is different and that's why failing preview build. So is there any way? 
and pardon me if I have used linting and formatting interchangeably 🥲

**Comment by Preet-Sojitra** [comment]
this is what I have found from `setting.json`  file of my vscode
image

**Comment by Lalit3716** [comment]
Yeah I think it's a good idea to setup prettier for `docs` too to avoid situations like this, what do you say @ayoayco ?

**Comment by Lalit3716** [comment]
Maybe we can go one step ahead and even setup husky to run prettier before commits!

**Comment by ayoayco** [comment]
Yes that sounds good. Just need to make sure everyone has the same eslint/prettier rules.

**Comment by ayoayco** [comment]
> Yeah I think it's a good idea to setup prettier for `docs` too to avoid situations like this, what do you say @ayoayco ?

Yes we need to do this too. I did not realize we don't have the eslint/prettier configuration for the docs app!

**Comment by Lalit3716** [comment]
Should I make a PR to setup this or @Preet-Sojitra do you want to do this in this PR?

**Comment by ayoayco** [comment]
Ah no worries. I will just merge this then write another issue for it :)

**Comment by Preet-Sojitra** [comment]
> Ah no worries. I will just merge this then write another issue for it :)

since you have merge this, won't it breaks the docs? because netlify was was showing `deploy preview failed`

**Comment by ayoayco** [comment]
> > Ah no worries. I will just merge this then write another issue for it :)
> 
> 
> 
> since you have merge this, won't it breaks the docs? because netlify was was showing `deploy preview failed`
> 
> 

Nope, that's okay because our "build and test" pipelines are still passing. The failed ones are just for the Netlify Preview links. And even if build fails on Metlify for this merge it will not affect the current deployed one. ;)

**Pull request merged**
