### PR TITLE
Adding test coverage for validator functions.

### LINKED ISSUE #149: test(validator): add tests for all validator functions
✨ Desired outcome: 100% test coverage for the validator functions ;) see the file in `packages/validator/core/validator-functions.ts`

### PR DESCRIPTION
**Pull request by Lalit3716**
## test(validators): Adding test coverage for validator functions.

Fixes #149  

Description of changes: 
- Added ts-mocha as dev dependency for supporting typescript test files.
- Added test suite for ValidatorFunctions.

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [ ] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by ayoayco** [comment]
Thanks @Lalit3716 I will go through this

**Comment by Lalit3716** [comment]
Hi, @ayoayco did you got time to go through this? If so were you able to import typescript files in the test files?

**Comment by Lalit3716** [comment]
That sounds like a nice idea! Still, I am not sure if we will be able to import ts files into test files 😅

**Comment by ayoayco** [comment]
It's because the tests we currently have are in js I think.

**Comment by ayoayco** [comment]
Hey @Lalit3716 I'm closing this PR for now. I want to reassess our testing toolset. What we have currently is specifically set up to test Astro components. Thank you so much for looking into this. It is still a huge contribution despite not turning out into a merged PR. We now know we need an improvement in our tooling. ❤️

**Pull request closed without merging**
