### PR TITLE
chore: Shared eslint + prettier for packages

### LINKED ISSUE #94: chore(packages): shared eslint rules
Set up the eslint configuration form all packages.

Right now we have separate eslint configuration for packages.

### PR DESCRIPTION
**Pull request by Lalit3716**
# chore(packages): Shared ESLint + Prettier configurations

Fixes #94  

Description of changes: 
- Initialized a npm package.json in root of packages.
- Added shared Eslint and Prettier configs.

Problems:
- Changes break the demo app as I don't why but somehow imports are getting messed up in demo app (help needed)

Tag a reviewer: @ayoayco 

Note:
Make sure to do a quick npm install after pulling changes.

Tasks:
- [x] I have ran the tests to make sure nothing is broken (see CONTRIBUTING.md)
- [x] I have ran the the linter to make sure code is clean (see CONTRIBUTING.md)
- [ ] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by Lalit3716** [comment]
Hi @ayoayco, I have successfully implemented shared eslint/prettier rules but for some reason, package imports are messed up now in the demo app. Can you please have a look and point me in the right direction?

**Comment by ayoayco** [comment]
hi @Lalit3716! can you check the failing build?

also if it is possible to keep the devDependencies in the package directories (packages/form, packages/validator)

**Comment by ayoayco** [comment]
thank you! let us know if you get problems

**Comment by Lalit3716** [comment]
Hi @ayoayco, I think it is best we make a separate package for our shareable config as documented here https://eslint.org/docs/latest/developer-guide/shareable-configs.

Because as it turns out it is not easy to share configs without making a root package

**Comment by Lalit3716** [comment]
My fault sorry that was really easy to do, I am just dumb lol 🤡

**Comment by ayoayco** [comment]
> My fault sorry that was really easy to do, I am just dumb lol 🤡

naaah we all get this sometimes. 🤣 


Is the problem with the demo app preventing it from running/building or just some warnings on VS code?

**Review by ayoayco — APPROVED** [review]
Haha looks great 👍 Thanks for this @Lalit3716!!!

**Pull request merged**
