### PR TITLE
fix(form): internal package on local dev environment symlinked to node_modules 

### LINKED ISSUE #239: fix(form): triggerValidationOn property is causing errors
When running "npm run check" which checks the types on .astro files, we get some errors caused by the property `triggerValidationOn`

Seems we need to update some types on the Form package to fix this

### PR DESCRIPTION
**Pull request by fazzaamiarso**
Fixes #239 

Description of changes: 
- change internal packages reference to use `*` instead of latest.
- turborepo `check` step depends on packages' build.

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by fazzaamiarso** [comment]
@ayoayco for sharing internal packages we should use `*`. Using `latest` will install the packages from the registry to their internal `node_modules` on dev.

To remove the wrong symlinks, we must delete the `package-lock.json` first and install afterwards.

**Comment by ayoayco** [comment]
Thanks for this @fazzaamiarso! I'm going to release a new version of our packages to npm. Do you think it is safe or better to tag it as a beta first?

**Review by ayoayco — APPROVED** [review]

**Comment by fazzaamiarso** [comment]
@ayoayco I think it's better to be safe and release the beta version first.

**Comment by ayoayco** [comment]
I tested this manually in a new app from scratch and decided we can release as we usually do, because we don't have a lot of users and the core features are still there anyway :)

**Pull request merged**
