### PR TITLE
[feat]: Add a new demo page

### LINKED ISSUE #68: [feat]: add a new demo page
Hi, explorer! 🚀

We have a `demo` app to play around with the packages (eg., astro-reactive-form).

Why not add some crazy examples? Create a new `.astro` page in the `pages` folder of the `demo` app. This new page will then be accessible on the browser. :)

For example, if you create a `crazy-form.astro` file in the `pages` directory, just open the address in the browser: `http://localhost:3000/crazy-form`

See our [contributing guide](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) for instructions to run the development server.

Read how to use the [reactive form package](https://github.com/ayoayco/astro-reactive-library/blob/main/packages/astro-reactive-form/README.md)

That's it! :)

Acceptance criteria:
1. a new .astro page in the demo app with as many different form control types as you can

### PR DESCRIPTION
**Pull request by itsagift**
#[feat]: Add a new demo page

Fixes #68  

Description of changes: 
- Created a new demo form for a hypothetical pizza shop. 
-

Tag a reviewer: @ayoayco 

Tasks:
- [X] I have ran the tests to make sure nothing is broken (see CONTRIBUTING.md)
- [X] I have ran the the linter to make sure code is clean (see CONTRIBUTING.md)
- [X] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by itsagift** [comment]
BTW -- I can create a separate issue for the bug, but radio groups don't work with multiple form groups (here I had a base form and toppings form). So technically this is a little broken, but the radio groups themselves work in a single form, and it should work great once that bug is fixed! I figured I'd submit anyway.

**Review by ayoayco — COMMENTED** [review]
I really like the idea of a demo page for a pizza ordering app! Can you maybe add another form group for information of the person ordering like Name, Delivery Address, and Contact number? Then I guess make the Address required 😁

**Comment by ayoayco** [comment]
> BTW -- I can create a separate issue for the bug...

please do create an issue describing the problem if you can, I have not personally seen it yet.

**Review by ayoayco — CHANGES_REQUESTED** [review]
Suggestion to also rename the page to `pizza-delivery.astro` 😁

**Review by ayoayco — APPROVED** [review]
Awesome work 🚀

**Pull request merged**
