### PR TITLE
ui(landing-page): Added astro section

### LINKED ISSUE #133: feat(landing-page): Add Astro Section
As discussed in #112

### PR DESCRIPTION
**Pull request by Lalit3716**
## ui(landing-page): Added Astro section on the landing page

Fixes #133  

Description of changes: 
- Added astro section as discussed in discussion #112 

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by ayoayco** [comment]
Ey @Lalit3716 thanks for the PR! Did you apply the dark background to the astro section? I can't run the brach to check right now...

**Comment by Lalit3716** [comment]
oops forgot to attach screenshot, here you go @ayoayco:

Screenshot 2022-10-27 214353

**Comment by Lalit3716** [comment]
Okay I will try it👍

**Comment by Lalit3716** [comment]
Hi @ayoayco, so it looks like this, let me know what do you think?

Screenshot 2022-10-28 122608

**Comment by ayoayco** [comment]
It looks good! @Lalit3716

**Review by ayoayco — APPROVED** [review]
Alright merging this. Thank you @Lalit3716 great work! 🚀

**Pull request merged**
