### PR TITLE
chore(library): implement turporepo

### LINKED ISSUE #2: [chore]: Set up the project monorepo
Hey, explorer! 🚀

Currently, the project is made up of [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), which are node projects that share a singular root package.

This issue is for setting up the project monorepo. Check the [CONTRIBUTING document](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) for how to contribute.

Acceptance criteria:
1. Recommend a monorepo library (e.g., Nx or Turborepo), indicating some rough pros and cons
2. Set up the agreed monorepo

That's it :) Another issue is for updating the docs to reflect the changes from this issue 👉 #3

### PR DESCRIPTION
**Pull request by ayoayco**
## chore(library): implement turborepo

Fixes #2 

Description of changes: 
- set up dependencies to implement turborepo
- update npm scripts

Tag a reviewer: @fazzaamiarso 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by fazzaamiarso** [comment]
@ayoayco I've tested them and they're looking good on my side. Do we need anything else? improve the docs maybe?

**Comment by ayoayco** [comment]
I think this one is ready. Any improvement needed can be worked on in other tasks.

Let me just see why the pipeline is failing 😅

**Comment by ayoayco** [comment]
@fazzaamiarso for some reason `turbo run test` was giving us a timeout error in the pipeline. This does not happen on the local though. What I did for now is create a new script "test-ci" which does the npm workspace commend `npm run test --workspaces --if-present` and this works, but we don't get the benefit of turbo running our tests in our pipelines. Maybe for another issue?

**Comment by fazzaamiarso** [comment]
@ayoayco  is it possible for me to get write access to this repo? I wanted to push to this branch but blocked

**Comment by ayoayco** [comment]
Merged! The branch is autodeleted

**Pull request merged**
