### PR TITLE
docs(codesandbox): added link to codesandbox example

### LINKED ISSUE #137: docs: add a link to a stackblitz example
Create a StackBlitz with example usage of our form and validator packages. 

Then update our README with a link to the StackBlitz :)

### PR DESCRIPTION
**Pull request by munyanezaarmel**
## docs(codesandbox): added link to codesandbox example 

Fixes #137 

Description of changes: 
- added link to codesandbox example 

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by ayoayco** [comment]
Looks good.  Not related to this PR, but can I ask you to change the Stackblitz link to show the `index.astro` file by default? It is currently opening Tour.astro 😅

`https://stackblitz.com/edit/github-ze9ebb-tthuka?file=package.json,src%2Fpages%2Findex.astro`

**Review by ayoayco — DISMISSED** [review]

**Comment by munyanezaarmel** [comment]
@ayoayco done

**Comment by munyanezaarmel** [comment]
done

**Review by ayoayco — APPROVED** [review]
Thanks for the great updates today! 🚀

**Pull request merged**
