### PR TITLE
feat(form): implement island components for each initial input controls

### LINKED ISSUE #11: feat(form): each control is an island (initial components)
Create an Astro component for each of the following input control types (i.e., possible values for `ControlBase.type` )

### PR DESCRIPTION
**Pull request by Icyscools**
## feat(form): implement island components for each initial input controls

Fixes #11 

In this feature, I heavily reuse the `Field.astro` as a base for each island component and it works like magic 🪄, only `RadioGroup.astro` I used the code in `Form.astro` with clean-up some code.

Description of changes:
- Implement island components for text, radio group, checkbox, and submit control.
- Add a `copy()` method in `FormControl` for copy the `FormControl` attributes. This method I use to copy and override some attributes to create a new `FormControl`.
- Add a `<slot>` tag in `Form.astro`.
- Add a `slot.astro` demo page to see how it worked.

Tag a reviewer: @ayoayco 

Tasks:
- [ ] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by ayoayco** [comment]
Looks like Typescript is complaining :) Can you check the errors?

**Comment by Icyscools** [comment]
Sure, I'll try to figure it out.

**Comment by ayoayco** [comment]
I just merged a clean up, maybe it will help clear things... Also made some control components including RadioGroup.astro :)

**Comment by Icyscools** [comment]
Ok, I think we can close this PR and I'll moving up to help on others features. ❤️

**Pull request closed without merging**
