### PR TITLE
fix: extends timeout for timed out test

### LINKED ISSUE #207: fix(ci): validator test timed out in CI with turborepo
### **Describe the bug**
In CI environment, running tests with `turbo` command causes timeout error, but works locally.

### PR DESCRIPTION
**Pull request by fazzaamiarso**
Fixes #207

Description of changes:
-  Add timeout and retry to failing test

Tag a reviewer: @ayoayco 

Tasks:
- [x] I have ran the build command to make sure apps are working: `npm run build`
- [x] I have ran the tests to make sure nothing is broken: `npm run test`
- [x] I have ran the linter to make sure code is clean: `npm run lint`
- [x] I have reviewed my own code to remove changes that are not needed

### CODE REVIEW

**Comment by fazzaamiarso** [comment]
@ayoayco seems like it broke when we tested against node 16.x. I will dig deeper tomorrow.

**Comment by ayoayco** [comment]
What did you find so far @fazzaamiarso?

**Comment by ayoayco** [comment]
Maybe we have hit a limit to github actions free tier?

**Comment by fazzaamiarso** [comment]
@ayoayco  apparently this is a known issue in vitest's repo [https://github.com/vitest-dev/vitest/issues/2008](https://github.com/vitest-dev/vitest/issues/2008). 

Setting extended timeout or disabling threads is the current workaround. I will make some final changes to this PR.

**Comment by ayoayco** [comment]
Okay thanks! What are we going for, extended timeout or disabled threads?

**Comment by fazzaamiarso** [comment]
> Okay thanks! What are we going for, extended timeout or disabled threads?

I think we should do both just to be safe for now.

**Comment by fazzaamiarso** [comment]
@ayoayco I think it's ready to be merged.

**Comment by ayoayco** [comment]
What's the implication for local development @fazzaamiarso? This means on local we will also have threads disabled?

**Comment by fazzaamiarso** [comment]
@ayoayco By disabling threads, our tests will be slower as they will be run sequentially. With that being said, we could conditionally disable the thread in CI by checking `process.env.CI`.

Should we do that?

**Comment by ayoayco** [comment]
Yes, I think if the problem is only seen on CI, let's only disable threads there... it's okay we don't have many PRs now. But for local development it would be great if we get full speed :) @fazzaamiarso

**Comment by fazzaamiarso** [comment]
@ayoayco It's done!

**Pull request merged**
